### ISSUE TITLE
[EPIC] gRPC JSON transcoding

### ISSUE THREAD

**Issue by JamesNK** [grpc/grpc-dotnet#1583]
Community issue - https://github.com/grpc/grpc-dotnet/issues/167

This issue is for tracking tasks. Separate from the community issue to avoid notification spam.

- [x] Rewrite serialization to use System.Text.Json
  - [x] Write converters for protobuf types
  - [x] Optimization
  - [x] Use new System.Text.Json .NET 7 features
- [x] Support server streaming
- [x] Support HttpBody messages - https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/httpbody_messages/
- [ ] Configuration
  - [ ] Unbound handlers - https://grpc-ecosystem.github.io/grpc-gateway/docs/mapping/grpc_api_configuration/
  - [x] JSON customization (e.g. formatting, long as string, type register, disallow unknown properties)
  - [ ] Error handler
- [ ] Swagger support
  - [ ] Option to output query parameters as swagger parameters
  - [x] Read XML docs as swagger docs
- [x] Move source to aspnetcore repo
- [x] Improve documentation
- [ ] Performance testing
- [x] Update Grpc.Core.Api to 2.45.0
  - [x] Remove nullable todos
  - [x] Support WriteAsync cancellation token
